### ISSUE TITLE
calibrate_data - Error in bold(i) : could not find function "bold"

### ISSUE THREAD

**Issue by cbonsell** [BLE-LTER/insitu#5]
Error in bold(i) : could not find function "bold"
3.
paste(bold(i), "station:", "\n\tFound", bold(length(cal_by_rows)), "calibration points from YSI data", "at:", blue(paste0(by_station[cal_by_rows, "date_time", drop = T], collapse = ", ")))
2.
message(paste(bold(i), "station:", "\n\tFound", bold(length(cal_by_rows)), "calibration points from YSI data", "at:", blue(paste0(by_station[cal_by_rows, "date_time", drop = T], collapse = ", "))))
1.
calibrate_data(to_cal, YSI, cal_by = "conductivity", raw = "conductivity")

**Comment by atn38** [comment]
faulty namespace, fixed now
