### ISSUE TITLE
flag_salinity still gives value TRUE

### ISSUE THREAD

**Issue by cbonsell** [BLE-LTER/insitu#6]
RBR <- flag_salinity(RBR, Terror=.002, Cerror = .01, flag_scheme = c("VALID","INV"))

works, but then

 table(RBR$station, RBR$anomalous)
       
         INV TRUE VALID
  EELD1    0 6364  2420
  EWLD2    0  627  8155
  JALD2    0  601  8215
  KALD2    0  536  8303

**Comment by atn38** [comment]
logical column was being converted to character prematurely, thus leaving
string "TRUE" values in output. now fixed
