### ISSUE TITLE
include test_data in package

### ISSUE THREAD

**Issue by atn38** [BLE-LTER/insitu#8]
@cbonsell I saw that you included a reference to `test_data` in `plot_TS()` example:

```r
plot.TS(test_data,"Temperature","Salinity","DT", plottitle="KALD1")
```

There are easy ways to include example data in R packages, see: http://r-pkgs.had.co.nz/data.html

**Comment by atn38** [comment]
@cbonsell see above commit. I also fixed the Roxygen @example. From now on if the package is loaded you can call `test_data` for the included data, which really is just the StarOddi raw data I grabbed off of the hydrography dataset.

**Comment by cbonsell** [comment]
great, thanks!
